//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AccountingKnowledgeDBModel", "FK_Client_Privilegy", "Privilegy", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Entity.EntityPrivilegy), "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Entity.EntityClient), true)]
[assembly: EdmRelationshipAttribute("AccountingKnowledgeDBModel", "FK_Resume_Client", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Entity.EntityClient), "Resume", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Entity.EntityResume), true)]
[assembly: EdmRelationshipAttribute("AccountingKnowledgeDBModel", "FK_Theme_FieldOfKnowledge", "FieldOfKnowledge", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Entity.EntityField), "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Entity.EntityTheme), true)]
[assembly: EdmRelationshipAttribute("AccountingKnowledgeDBModel", "FK_ResumeTheme_Resume", "Resume", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Entity.EntityResume), "ResumeTheme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Entity.EntityResumeTheme), true)]
[assembly: EdmRelationshipAttribute("AccountingKnowledgeDBModel", "FK_ResumeTheme_Theme", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Entity.EntityTheme), "ResumeTheme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Entity.EntityResumeTheme), true)]
[assembly: EdmRelationshipAttribute("AccountingKnowledgeDBModel", "FK_Skill_Skill", "SkillGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Entity.EntitySkillGroup), "Skill", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Entity.EntitySkill), true)]
[assembly: EdmRelationshipAttribute("AccountingKnowledgeDBModel", "FK_Theme_SkillGroup", "SkillGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccessLayer.Entity.EntitySkillGroup), "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Entity.EntityTheme), true)]

#endregion

namespace DataAccessLayer.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AkDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AkDbEntities object using the connection string found in the 'AkDbEntities' section of the application configuration file.
        /// </summary>
        public AkDbEntities() : base("name=AkDbEntities", "AkDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AkDbEntities object.
        /// </summary>
        public AkDbEntities(string connectionString) : base(connectionString, "AkDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AkDbEntities object.
        /// </summary>
        public AkDbEntities(EntityConnection connection) : base(connection, "AkDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntityClient> Client
        {
            get
            {
                if ((_Client == null))
                {
                    _Client = base.CreateObjectSet<EntityClient>("Client");
                }
                return _Client;
            }
        }
        private ObjectSet<EntityClient> _Client;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntityField> FieldOfKnowledge
        {
            get
            {
                if ((_FieldOfKnowledge == null))
                {
                    _FieldOfKnowledge = base.CreateObjectSet<EntityField>("FieldOfKnowledge");
                }
                return _FieldOfKnowledge;
            }
        }
        private ObjectSet<EntityField> _FieldOfKnowledge;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntityPrivilegy> Privilegy
        {
            get
            {
                if ((_Privilegy == null))
                {
                    _Privilegy = base.CreateObjectSet<EntityPrivilegy>("Privilegy");
                }
                return _Privilegy;
            }
        }
        private ObjectSet<EntityPrivilegy> _Privilegy;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntityResume> Resume
        {
            get
            {
                if ((_Resume == null))
                {
                    _Resume = base.CreateObjectSet<EntityResume>("Resume");
                }
                return _Resume;
            }
        }
        private ObjectSet<EntityResume> _Resume;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntityResumeTheme> ResumeTheme
        {
            get
            {
                if ((_ResumeTheme == null))
                {
                    _ResumeTheme = base.CreateObjectSet<EntityResumeTheme>("ResumeTheme");
                }
                return _ResumeTheme;
            }
        }
        private ObjectSet<EntityResumeTheme> _ResumeTheme;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntitySkill> Skill
        {
            get
            {
                if ((_Skill == null))
                {
                    _Skill = base.CreateObjectSet<EntitySkill>("Skill");
                }
                return _Skill;
            }
        }
        private ObjectSet<EntitySkill> _Skill;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntitySkillGroup> SkillGroup
        {
            get
            {
                if ((_SkillGroup == null))
                {
                    _SkillGroup = base.CreateObjectSet<EntitySkillGroup>("SkillGroup");
                }
                return _SkillGroup;
            }
        }
        private ObjectSet<EntitySkillGroup> _SkillGroup;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntityTheme> Theme
        {
            get
            {
                if ((_Theme == null))
                {
                    _Theme = base.CreateObjectSet<EntityTheme>("Theme");
                }
                return _Theme;
            }
        }
        private ObjectSet<EntityTheme> _Theme;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Client EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClient(EntityClient entityClient)
        {
            base.AddObject("Client", entityClient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FieldOfKnowledge EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFieldOfKnowledge(EntityField entityField)
        {
            base.AddObject("FieldOfKnowledge", entityField);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Privilegy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrivilegy(EntityPrivilegy entityPrivilegy)
        {
            base.AddObject("Privilegy", entityPrivilegy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Resume EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResume(EntityResume entityResume)
        {
            base.AddObject("Resume", entityResume);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ResumeTheme EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResumeTheme(EntityResumeTheme entityResumeTheme)
        {
            base.AddObject("ResumeTheme", entityResumeTheme);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Skill EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSkill(EntitySkill entitySkill)
        {
            base.AddObject("Skill", entitySkill);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SkillGroup EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSkillGroup(EntitySkillGroup entitySkillGroup)
        {
            base.AddObject("SkillGroup", entitySkillGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Theme EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTheme(EntityTheme entityTheme)
        {
            base.AddObject("Theme", entityTheme);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountingKnowledgeDBModel", Name="EntityClient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityClient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityClient object.
        /// </summary>
        /// <param name="clientID">Initial value of the ClientID property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="pass">Initial value of the Pass property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="secondName">Initial value of the SecondName property.</param>
        /// <param name="birthDay">Initial value of the BirthDay property.</param>
        /// <param name="phoneNumber">Initial value of the PhoneNumber property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="privilegyID">Initial value of the PrivilegyID property.</param>
        public static EntityClient CreateEntityClient(global::System.Int32 clientID, global::System.String login, global::System.String pass, global::System.String firstName, global::System.String secondName, global::System.DateTime birthDay, global::System.String phoneNumber, global::System.String email, global::System.Int16 privilegyID)
        {
            EntityClient entityClient = new EntityClient();
            entityClient.ClientID = clientID;
            entityClient.Login = login;
            entityClient.Pass = pass;
            entityClient.FirstName = firstName;
            entityClient.SecondName = secondName;
            entityClient.BirthDay = birthDay;
            entityClient.PhoneNumber = phoneNumber;
            entityClient.Email = email;
            entityClient.PrivilegyID = privilegyID;
            return entityClient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientID
        {
            get
            {
                return _ClientID;
            }
            set
            {
                if (_ClientID != value)
                {
                    OnClientIDChanging(value);
                    ReportPropertyChanging("ClientID");
                    _ClientID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClientID");
                    OnClientIDChanged();
                }
            }
        }
        private global::System.Int32 _ClientID;
        partial void OnClientIDChanging(global::System.Int32 value);
        partial void OnClientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pass
        {
            get
            {
                return _Pass;
            }
            set
            {
                OnPassChanging(value);
                ReportPropertyChanging("Pass");
                _Pass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pass");
                OnPassChanged();
            }
        }
        private global::System.String _Pass;
        partial void OnPassChanging(global::System.String value);
        partial void OnPassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecondName
        {
            get
            {
                return _SecondName;
            }
            set
            {
                OnSecondNameChanging(value);
                ReportPropertyChanging("SecondName");
                _SecondName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SecondName");
                OnSecondNameChanged();
            }
        }
        private global::System.String _SecondName;
        partial void OnSecondNameChanging(global::System.String value);
        partial void OnSecondNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BirthDay
        {
            get
            {
                return _BirthDay;
            }
            set
            {
                OnBirthDayChanging(value);
                ReportPropertyChanging("BirthDay");
                _BirthDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BirthDay");
                OnBirthDayChanged();
            }
        }
        private global::System.DateTime _BirthDay;
        partial void OnBirthDayChanging(global::System.DateTime value);
        partial void OnBirthDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 PrivilegyID
        {
            get
            {
                return _PrivilegyID;
            }
            set
            {
                OnPrivilegyIDChanging(value);
                ReportPropertyChanging("PrivilegyID");
                _PrivilegyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrivilegyID");
                OnPrivilegyIDChanged();
            }
        }
        private global::System.Int16 _PrivilegyID;
        partial void OnPrivilegyIDChanging(global::System.Int16 value);
        partial void OnPrivilegyIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_Client_Privilegy", "Privilegy")]
        public EntityPrivilegy Privilegy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityPrivilegy>("AccountingKnowledgeDBModel.FK_Client_Privilegy", "Privilegy").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityPrivilegy>("AccountingKnowledgeDBModel.FK_Client_Privilegy", "Privilegy").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityPrivilegy> PrivilegyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityPrivilegy>("AccountingKnowledgeDBModel.FK_Client_Privilegy", "Privilegy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityPrivilegy>("AccountingKnowledgeDBModel.FK_Client_Privilegy", "Privilegy", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_Resume_Client", "Resume")]
        public EntityCollection<EntityResume> Resume
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntityResume>("AccountingKnowledgeDBModel.FK_Resume_Client", "Resume");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntityResume>("AccountingKnowledgeDBModel.FK_Resume_Client", "Resume", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountingKnowledgeDBModel", Name="EntityField")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityField : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityField object.
        /// </summary>
        /// <param name="fieldID">Initial value of the FieldID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static EntityField CreateEntityField(global::System.Int32 fieldID, global::System.String title)
        {
            EntityField entityField = new EntityField();
            entityField.FieldID = fieldID;
            entityField.Title = title;
            return entityField;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FieldID
        {
            get
            {
                return _FieldID;
            }
            set
            {
                if (_FieldID != value)
                {
                    OnFieldIDChanging(value);
                    ReportPropertyChanging("FieldID");
                    _FieldID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FieldID");
                    OnFieldIDChanged();
                }
            }
        }
        private global::System.Int32 _FieldID;
        partial void OnFieldIDChanging(global::System.Int32 value);
        partial void OnFieldIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_Theme_FieldOfKnowledge", "Theme")]
        public EntityCollection<EntityTheme> Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntityTheme>("AccountingKnowledgeDBModel.FK_Theme_FieldOfKnowledge", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntityTheme>("AccountingKnowledgeDBModel.FK_Theme_FieldOfKnowledge", "Theme", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountingKnowledgeDBModel", Name="EntityPrivilegy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityPrivilegy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityPrivilegy object.
        /// </summary>
        /// <param name="privilegyID">Initial value of the PrivilegyID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static EntityPrivilegy CreateEntityPrivilegy(global::System.Int16 privilegyID, global::System.String title)
        {
            EntityPrivilegy entityPrivilegy = new EntityPrivilegy();
            entityPrivilegy.PrivilegyID = privilegyID;
            entityPrivilegy.Title = title;
            return entityPrivilegy;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 PrivilegyID
        {
            get
            {
                return _PrivilegyID;
            }
            set
            {
                if (_PrivilegyID != value)
                {
                    OnPrivilegyIDChanging(value);
                    ReportPropertyChanging("PrivilegyID");
                    _PrivilegyID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PrivilegyID");
                    OnPrivilegyIDChanged();
                }
            }
        }
        private global::System.Int16 _PrivilegyID;
        partial void OnPrivilegyIDChanging(global::System.Int16 value);
        partial void OnPrivilegyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_Client_Privilegy", "Client")]
        public EntityCollection<EntityClient> Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntityClient>("AccountingKnowledgeDBModel.FK_Client_Privilegy", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntityClient>("AccountingKnowledgeDBModel.FK_Client_Privilegy", "Client", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountingKnowledgeDBModel", Name="EntityResume")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityResume : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityResume object.
        /// </summary>
        /// <param name="resumeID">Initial value of the ResumeID property.</param>
        /// <param name="clientID">Initial value of the ClientID property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static EntityResume CreateEntityResume(global::System.Int32 resumeID, global::System.Int32 clientID, global::System.DateTime date, global::System.String title, global::System.String description)
        {
            EntityResume entityResume = new EntityResume();
            entityResume.ResumeID = resumeID;
            entityResume.ClientID = clientID;
            entityResume.Date = date;
            entityResume.Title = title;
            entityResume.Description = description;
            return entityResume;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResumeID
        {
            get
            {
                return _ResumeID;
            }
            set
            {
                if (_ResumeID != value)
                {
                    OnResumeIDChanging(value);
                    ReportPropertyChanging("ResumeID");
                    _ResumeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResumeID");
                    OnResumeIDChanged();
                }
            }
        }
        private global::System.Int32 _ResumeID;
        partial void OnResumeIDChanging(global::System.Int32 value);
        partial void OnResumeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientID
        {
            get
            {
                return _ClientID;
            }
            set
            {
                OnClientIDChanging(value);
                ReportPropertyChanging("ClientID");
                _ClientID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientID");
                OnClientIDChanged();
            }
        }
        private global::System.Int32 _ClientID;
        partial void OnClientIDChanging(global::System.Int32 value);
        partial void OnClientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_Resume_Client", "Client")]
        public EntityClient Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityClient>("AccountingKnowledgeDBModel.FK_Resume_Client", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityClient>("AccountingKnowledgeDBModel.FK_Resume_Client", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityClient> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityClient>("AccountingKnowledgeDBModel.FK_Resume_Client", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityClient>("AccountingKnowledgeDBModel.FK_Resume_Client", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_ResumeTheme_Resume", "ResumeTheme")]
        public EntityCollection<EntityResumeTheme> ResumeTheme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntityResumeTheme>("AccountingKnowledgeDBModel.FK_ResumeTheme_Resume", "ResumeTheme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntityResumeTheme>("AccountingKnowledgeDBModel.FK_ResumeTheme_Resume", "ResumeTheme", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountingKnowledgeDBModel", Name="EntityResumeTheme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityResumeTheme : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityResumeTheme object.
        /// </summary>
        /// <param name="resumeThemeID">Initial value of the ResumeThemeID property.</param>
        /// <param name="resumeID">Initial value of the ResumeID property.</param>
        /// <param name="skillID">Initial value of the SkillID property.</param>
        /// <param name="themeID">Initial value of the ThemeID property.</param>
        public static EntityResumeTheme CreateEntityResumeTheme(global::System.Int32 resumeThemeID, global::System.Int32 resumeID, global::System.Int32 skillID, global::System.Int32 themeID)
        {
            EntityResumeTheme entityResumeTheme = new EntityResumeTheme();
            entityResumeTheme.ResumeThemeID = resumeThemeID;
            entityResumeTheme.ResumeID = resumeID;
            entityResumeTheme.SkillID = skillID;
            entityResumeTheme.ThemeID = themeID;
            return entityResumeTheme;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResumeThemeID
        {
            get
            {
                return _ResumeThemeID;
            }
            set
            {
                if (_ResumeThemeID != value)
                {
                    OnResumeThemeIDChanging(value);
                    ReportPropertyChanging("ResumeThemeID");
                    _ResumeThemeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResumeThemeID");
                    OnResumeThemeIDChanged();
                }
            }
        }
        private global::System.Int32 _ResumeThemeID;
        partial void OnResumeThemeIDChanging(global::System.Int32 value);
        partial void OnResumeThemeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResumeID
        {
            get
            {
                return _ResumeID;
            }
            set
            {
                OnResumeIDChanging(value);
                ReportPropertyChanging("ResumeID");
                _ResumeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResumeID");
                OnResumeIDChanged();
            }
        }
        private global::System.Int32 _ResumeID;
        partial void OnResumeIDChanging(global::System.Int32 value);
        partial void OnResumeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SkillID
        {
            get
            {
                return _SkillID;
            }
            set
            {
                OnSkillIDChanging(value);
                ReportPropertyChanging("SkillID");
                _SkillID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SkillID");
                OnSkillIDChanged();
            }
        }
        private global::System.Int32 _SkillID;
        partial void OnSkillIDChanging(global::System.Int32 value);
        partial void OnSkillIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ThemeID
        {
            get
            {
                return _ThemeID;
            }
            set
            {
                OnThemeIDChanging(value);
                ReportPropertyChanging("ThemeID");
                _ThemeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThemeID");
                OnThemeIDChanged();
            }
        }
        private global::System.Int32 _ThemeID;
        partial void OnThemeIDChanging(global::System.Int32 value);
        partial void OnThemeIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_ResumeTheme_Resume", "Resume")]
        public EntityResume Resume
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityResume>("AccountingKnowledgeDBModel.FK_ResumeTheme_Resume", "Resume").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityResume>("AccountingKnowledgeDBModel.FK_ResumeTheme_Resume", "Resume").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityResume> ResumeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityResume>("AccountingKnowledgeDBModel.FK_ResumeTheme_Resume", "Resume");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityResume>("AccountingKnowledgeDBModel.FK_ResumeTheme_Resume", "Resume", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_ResumeTheme_Theme", "Theme")]
        public EntityTheme Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityTheme>("AccountingKnowledgeDBModel.FK_ResumeTheme_Theme", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityTheme>("AccountingKnowledgeDBModel.FK_ResumeTheme_Theme", "Theme").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityTheme> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityTheme>("AccountingKnowledgeDBModel.FK_ResumeTheme_Theme", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityTheme>("AccountingKnowledgeDBModel.FK_ResumeTheme_Theme", "Theme", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountingKnowledgeDBModel", Name="EntitySkill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntitySkill : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntitySkill object.
        /// </summary>
        /// <param name="skillID">Initial value of the SkillID property.</param>
        /// <param name="groupID">Initial value of the GroupID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static EntitySkill CreateEntitySkill(global::System.Int32 skillID, global::System.Int32 groupID, global::System.String title)
        {
            EntitySkill entitySkill = new EntitySkill();
            entitySkill.SkillID = skillID;
            entitySkill.GroupID = groupID;
            entitySkill.Title = title;
            return entitySkill;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SkillID
        {
            get
            {
                return _SkillID;
            }
            set
            {
                if (_SkillID != value)
                {
                    OnSkillIDChanging(value);
                    ReportPropertyChanging("SkillID");
                    _SkillID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SkillID");
                    OnSkillIDChanged();
                }
            }
        }
        private global::System.Int32 _SkillID;
        partial void OnSkillIDChanging(global::System.Int32 value);
        partial void OnSkillIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                OnGroupIDChanging(value);
                ReportPropertyChanging("GroupID");
                _GroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupID");
                OnGroupIDChanged();
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_Skill_Skill", "SkillGroup")]
        public EntitySkillGroup SkillGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntitySkillGroup>("AccountingKnowledgeDBModel.FK_Skill_Skill", "SkillGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntitySkillGroup>("AccountingKnowledgeDBModel.FK_Skill_Skill", "SkillGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntitySkillGroup> SkillGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntitySkillGroup>("AccountingKnowledgeDBModel.FK_Skill_Skill", "SkillGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntitySkillGroup>("AccountingKnowledgeDBModel.FK_Skill_Skill", "SkillGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountingKnowledgeDBModel", Name="EntitySkillGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntitySkillGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntitySkillGroup object.
        /// </summary>
        /// <param name="groupID">Initial value of the GroupID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static EntitySkillGroup CreateEntitySkillGroup(global::System.Int32 groupID, global::System.String title)
        {
            EntitySkillGroup entitySkillGroup = new EntitySkillGroup();
            entitySkillGroup.GroupID = groupID;
            entitySkillGroup.Title = title;
            return entitySkillGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_Skill_Skill", "Skill")]
        public EntityCollection<EntitySkill> Skill
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntitySkill>("AccountingKnowledgeDBModel.FK_Skill_Skill", "Skill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntitySkill>("AccountingKnowledgeDBModel.FK_Skill_Skill", "Skill", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_Theme_SkillGroup", "Theme")]
        public EntityCollection<EntityTheme> Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntityTheme>("AccountingKnowledgeDBModel.FK_Theme_SkillGroup", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntityTheme>("AccountingKnowledgeDBModel.FK_Theme_SkillGroup", "Theme", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountingKnowledgeDBModel", Name="EntityTheme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityTheme : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityTheme object.
        /// </summary>
        /// <param name="themeID">Initial value of the ThemeID property.</param>
        /// <param name="fieldID">Initial value of the FieldID property.</param>
        /// <param name="groupID">Initial value of the GroupID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static EntityTheme CreateEntityTheme(global::System.Int32 themeID, global::System.Int32 fieldID, global::System.Int32 groupID, global::System.String title)
        {
            EntityTheme entityTheme = new EntityTheme();
            entityTheme.ThemeID = themeID;
            entityTheme.FieldID = fieldID;
            entityTheme.GroupID = groupID;
            entityTheme.Title = title;
            return entityTheme;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ThemeID
        {
            get
            {
                return _ThemeID;
            }
            set
            {
                if (_ThemeID != value)
                {
                    OnThemeIDChanging(value);
                    ReportPropertyChanging("ThemeID");
                    _ThemeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ThemeID");
                    OnThemeIDChanged();
                }
            }
        }
        private global::System.Int32 _ThemeID;
        partial void OnThemeIDChanging(global::System.Int32 value);
        partial void OnThemeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FieldID
        {
            get
            {
                return _FieldID;
            }
            set
            {
                OnFieldIDChanging(value);
                ReportPropertyChanging("FieldID");
                _FieldID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FieldID");
                OnFieldIDChanged();
            }
        }
        private global::System.Int32 _FieldID;
        partial void OnFieldIDChanging(global::System.Int32 value);
        partial void OnFieldIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                OnGroupIDChanging(value);
                ReportPropertyChanging("GroupID");
                _GroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupID");
                OnGroupIDChanged();
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_Theme_FieldOfKnowledge", "FieldOfKnowledge")]
        public EntityField FieldOfKnowledge
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityField>("AccountingKnowledgeDBModel.FK_Theme_FieldOfKnowledge", "FieldOfKnowledge").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityField>("AccountingKnowledgeDBModel.FK_Theme_FieldOfKnowledge", "FieldOfKnowledge").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntityField> FieldOfKnowledgeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntityField>("AccountingKnowledgeDBModel.FK_Theme_FieldOfKnowledge", "FieldOfKnowledge");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntityField>("AccountingKnowledgeDBModel.FK_Theme_FieldOfKnowledge", "FieldOfKnowledge", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_ResumeTheme_Theme", "ResumeTheme")]
        public EntityCollection<EntityResumeTheme> ResumeTheme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntityResumeTheme>("AccountingKnowledgeDBModel.FK_ResumeTheme_Theme", "ResumeTheme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntityResumeTheme>("AccountingKnowledgeDBModel.FK_ResumeTheme_Theme", "ResumeTheme", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountingKnowledgeDBModel", "FK_Theme_SkillGroup", "SkillGroup")]
        public EntitySkillGroup SkillGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntitySkillGroup>("AccountingKnowledgeDBModel.FK_Theme_SkillGroup", "SkillGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntitySkillGroup>("AccountingKnowledgeDBModel.FK_Theme_SkillGroup", "SkillGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntitySkillGroup> SkillGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntitySkillGroup>("AccountingKnowledgeDBModel.FK_Theme_SkillGroup", "SkillGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntitySkillGroup>("AccountingKnowledgeDBModel.FK_Theme_SkillGroup", "SkillGroup", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
